# Generated by Django 5.2.15 on 2026-07-24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teamshifts", "0010_remove_shift_capacity_remove_shift_role_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="teammemberapplication",
            name="arrived",
            field=models.BooleanField(default=False, help_text="Indicates if the team member has arrived on the event day.", verbose_name="Arrived"),
        ),
    ]
