# Generated by Django 5.2.16 on 2026-07-23 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teamshifts', '0010_remove_shift_capacity_remove_shift_role_and_more'),
        ('teamshifts', '0012_teamrole_is_restricted'),
    ]

    operations = [
    ]
