# Generated by Django 5.2.16 on 2026-07-29 09:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("teamshifts", "0011_teammemberapplication_arrived_and_more"),
        ("teamshifts", "0013_merge_20260723_1920"),
    ]

    operations = []
