# Generated by Django 5.2.16 on 2026-08-10 14:33

import django.db.models.deletion
import i18nfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0052_admission_validity_fields"),
        ("teamshifts", "0014_teamrole_is_restricted"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamShiftsCustomEmailTemplate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
                ("subject", i18nfield.fields.I18nTextField()),
                ("body", i18nfield.fields.I18nTextField()),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("event", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="teamshifts_custom_email_templates", to="base.event")),
            ],
            options={
                "verbose_name": "Custom email template",
                "verbose_name_plural": "Custom email templates",
                "ordering": ["name"],
            },
        ),
    ]
